services:
  mysql:
    image: mysql:8.0
    container_name: bill-service_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bill_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  bill-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bill-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bill_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: on-failure

volumes:
  mysql_data: